const CATALOG = [
  { title: "Homem-Aranha: Um Novo Dia", year: 2026, type: "filme", image: "assets/imgi_3_x0nvYzQpyJc5pdT9lMnkMuYAg0O.jpeg", url: "" },
  { title: "A Morte de Robin Hood", year: 2026, type: "filme", image: "assets/imgi_4_o0QndnepFPWget2kdKpzh26RBYt.jpeg", url: "" },
  { title: "A Odisseia", year: 2026, type: "filme", image: "assets/imgi_5_m0ehGErq8GTLK4WZxaq9QLGAR3u.jpeg", url: "" },
  { title: "A Morte do Demônio em Chamas", year: 2026, type: "filme", image: "assets/imgi_6_fteLdvfRnltfLjAEnsl5E3vImnW.jpeg", url: "" },
  { title: "Moana", year: 2026, type: "filme", image: "assets/imgi_7_tPDgn32iTONXzHo3a4Z0KAMOJfD.jpeg", url: "" },
  { title: "Minions: Monstros", year: 2026, type: "filme", image: "assets/imgi_8_hTowtXrkCY7FJyoj4p91JckrJSE.jpeg", url: "" },
  { title: "Avatar: O Último Mestre do Ar", year: 2024, type: "serie", image: "assets/imgi_9_zCz483fU94RxRt1gdGW1rxQkcID.jpeg", url: "" },
  { title: "A Casa do Dragão", year: 2022, type: "serie", image: "assets/imgi_10_xEC4nyJvcWcOu7QaobLcqz6iRUL.jpeg", url: "" },
  { title: "A Lenda de Vox Machina", year: 2022, type: "serie", image: "assets/imgi_11_hgQ1sQybq3pvdQcaYE18TR3CqRL.jpeg", url: "" },
  { title: "Spider Noir", year: 2026, type: "serie", image: "assets/imgi_12_rfrzXSaiuvRMLo8PRQds0TfFrZC.jpeg", url: "" },
  { title: "Impuros", year: 2018, type: "serie", image: "assets/imgi_13_vgdOEAAtH9hyJ5mZye8uKMaFV0X.jpeg", url: "" },
  { title: "Origem", year: 2022, type: "serie", image: "assets/imgi_14_j4DJV91VGx7eAIWPeolV0nOtT1G.jpeg", url: "" },
  { title: "O Poder do Rosário", year: 2026, type: "filme", image: "assets/imgi_15_l4ijzBon0y4woXqHeCaHyNFIvHp.jpeg", url: "" },
  { title: "Lapua 1976", year: 2023, type: "filme", image: "assets/imgi_16_1xSS5jLQNnpG5L9CafPJwFDw02a.jpeg", url: "" },
  { title: "Black Power: De Volta ao Sul", year: 2023, type: "filme", image: "assets/imgi_17_9ih2MxdnmVql8vyCGjntBXB0hO4.jpeg", url: "" },
  { title: "Triunfo no Madison Square Garden", year: 2022, type: "filme", image: "assets/imgi_18_9usehYSjDL8ePmzu4RwkhYonN8M.jpeg", url: "" },
  { title: "Jovens Águias", year: 2022, type: "filme", image: "assets/imgi_19_pZQq1WmFzvP3DGzG1fWUeSmOSvJ.jpeg", url: "" },
  { title: "Infantaria", year: 2022, type: "filme", image: "assets/imgi_20_9HPKnssvAXH0Tnybv88gIEP2eT4.jpeg", url: "" },
  { title: "A Heroína da Fita", year: 2026, type: "filme", image: "assets/imgi_21_sLjm1n06TuQnwT0XJp9YcvIMq44.jpeg", url: "" },
  { title: "Corrida dos Bichos", year: 2026, type: "filme", image: "assets/imgi_22_2bzIygGnua4tlLo7qTyMSUsME3d.jpeg", url: "" },
  { title: "Animales", year: 2026, type: "filme", image: "assets/imgi_23_wOnhgV3RZJhpOMA5b3LWBcfMncB.jpeg", url: "" },
  { title: "Vida Privada", year: 2025, type: "filme", image: "assets/imgi_24_hMObSFdPA5Y9gDysis7X2JVxIA5.jpeg", url: "" },
  { title: "Diva Futura", year: 2025, type: "filme", image: "assets/imgi_25_qLfdMy5LmUlkqgm3jvgVvIbvQWO.jpeg", url: "" },
  { title: "Operação Raqqa", year: 2024, type: "filme", image: "assets/imgi_26_22q38ZRTvjry2XjMBUBYXL6ZkSc.jpeg", url: "" },
  { title: "Os Escolhidos: À Prova de Tudo", year: 2026, type: "serie", image: "assets/imgi_27_cqphtX3b4tw1yG99EfVplMNjVgR.jpeg", url: "" },
  { title: "O Iluminado", year: 1997, type: "serie", image: "assets/imgi_28_wzPRTPYMiGqOdXooX3VRyls75Oc.jpeg", url: "" },
  { title: "Mortos S/A", year: 2024, type: "serie", image: "assets/imgi_29_7r61uEjUyJiNrbrqV0lh311LVZn.jpeg", url: "" },
  { title: "Voepass 2283: A Queda", year: 2026, type: "serie", image: "assets/imgi_30_dabQO1pa75oxSkMQ3CoRbNpWapU.jpeg", url: "" },
  { title: "Um Grude de Amor", year: 2026, type: "serie", image: "assets/imgi_31_qITVjM7ETkIH0l8WoIApSrzDjgu.jpeg", url: "" },
  { title: "Gatos de Rua de Ricky Gervais", year: 2026, type: "serie", image: "assets/imgi_32_ugFj2ulrmGJuGqj30yWMjY38SVL.jpeg", url: "" },
  { title: "Operação Safed Sagar", year: 2026, type: "serie", image: "assets/imgi_33_4WY3PUTWEeyVrBHaoYmd5H3XZtU.jpeg", url: "" },
  { title: "Monstros de Deus", year: 2026, type: "serie", image: "assets/imgi_34_zQSXfv1GiLJW2kszQUNMyrZGoqF.jpeg", url: "" },
  { title: "Alex Inc", year: 2018, type: "serie", image: "assets/imgi_35_uDrUGwYPV5qsE1ZxoQivOLOMWmv.jpeg", url: "" },
  { title: "Estilhaços", year: 2026, type: "serie", image: "assets/imgi_36_hMkkiXVwiGcJ5yF1kcsN7LUEDXu.jpeg", url: "" },
  { title: "The Challenge UK", year: 2023, type: "serie", image: "assets/imgi_37_l9SjZTOxjxySaitn85nDDKEclY2.jpeg", url: "" },
  { title: "Anna Karenina", year: 2017, type: "serie", image: "assets/imgi_38_zIr9LZso0o4NI2uzl7WVpjlSCU9.jpeg", url: "" }
];
